### ISSUE TITLE
Support for any URLs

### ISSUE THREAD

**Issue by pun-ky** [ModusCreateOrg/gimbal#151]
is this tool supporting only applications deployed on localhost?

https://github.com/ModusCreateOrg/gimbal/blob/master/packages/gimbal/src/command/lighthouse/index.ts#L16

I am developing an app available through domain also hosted on my local machine, but...
 using `localhost:xxxx` / using port number cannot be done... instead I am forced to use `http://example.com` let's say..

this audits configured within single configuration file looks nice and I'd like to try them but... don't know how... looks like that `localhost` is just hardcoded... :/

**Comment by mitchellsimoens** [comment]
Just a heads up, we are working on a v2 that is going to support it (just landed in my open PR). If you have any more great ideas, contribute to #158 to see if we can get to it!

**Comment by pun-ky** [comment]
ok thx
